name: FCS Scan
on: workflow_dispatch

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run FCS IaC Scan
        id: fcs-scan
        uses: crowdstrike/fcs-action@v2.0.3
        continue-on-error: true
        with:
          falcon_client_id: ${{ vars.FALCON_CLIENT_ID }}
          falcon_region: 'us-1'
          path: './samples'
          report_formats: 'sarif'
          output_path: './results.sarif'
          upload_results: true
          project_owners: 'gonzalo.rocamador@crowdstrike.com'
          project_name: 'groca-iac'
        env:
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

      - name: Upload SARIF results to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('./results.sarif') != ''
        with:
          sarif_file: './results.sarif'
